import type { Step } from "./types";

export const STEPS: Step[] = [
  // ── TAB 1: SETUP ─────────────────────────────────────────
  {
    id: "step-1",
    globalNumber: 1,
    tabId: "setup",
    label: "01 / Setup",
    title: "Download & Install",
    description: "RAVA is live on the Google Play Store. Tap the button below to install it directly on your Android device.",
    actionItems: [
      "Tap the Download button below to open RAVA on the Play Store",
      "Tap Install and wait for the download to complete",
      "Open RAVA from your home screen or app drawer",
    ],
    videoUrl: "https://www.youtube.com/embed/IMtgGjJLW-k?rel=0&modestbranding=1",
    downloadUrl: "https://play.google.com/store/apps/details?id=com.sedoid.rava",
    warning:
      "This is an early beta — some features may be incomplete or behave unexpectedly. Your honest feedback at each step is what shapes the final product.",
    warningColor: "#8C52FF",
    capturesIdentity: true,
    trackLabel: "Download & Install",
    notesPlaceholder: "Any issues during install?",
  },
  {
    id: "step-2",
    globalNumber: 2,
    tabId: "setup",
    label: "02 / Setup",
    title: "Onboarding & Sign In",
    description: "Complete the welcome flow and sign in to your RAVA account.",
    actionItems: [
      "Swipe through the welcome screens",
      "On the permissions screen, tap Allow for all requested permissions",
      "Select your preferred authentication method — phone number, Google account, or anonymous",
      "If you chose phone number, enter the OTP sent to your phone via SMS",
      "Select the currency of your region",
    ],
    videoUrl: "https://www.youtube.com/embed/9OvotN6HLYw?rel=0&modestbranding=1",
    warning:
      "The currency you select here will be used as the default across the entire app. Choose carefully — this affects how all your transactions and budgets are displayed.",
    warningColor: "#FF9F43",
    trackLabel: "Onboarding & Sign In",
    notesPlaceholder: "Any step that felt confusing or broke?",
  },
  {
    id: "step-3",
    globalNumber: 3,
    tabId: "setup",
    label: "03 / Setup",
    title: "Grant Access & Import",
    description: "Grant the necessary permissions so RAVA can detect and import your transactions.",
    actionItems: [
      "When prompted for SMS, Notifications, and Phone permissions, tap Allow",
      "On the Select Accounts screen, choose your provider — MTN MoMo, Orange Money, or both",
      "Click on continue and wait for the app to scan and import your transaction history",
      "Confirm transactions are appearing in the app",
      "To verify a specific transaction → navigate to Transs → tap the Search box → search by sender name, amount, or phone number",
    ],
    videoUrl: "https://www.youtube.com/embed/9GW3BqNnqIA?rel=0&modestbranding=1",
    warning:
      "Do not close or interfere with the app while your data is loading. This usually takes a few seconds, but may take a couple of minutes if you have a large transaction history.",
    warningColor: "#FF9F43",
    trackLabel: "Grant Access & Import",
    notesPlaceholder:
      "Did your transactions import correctly? Roughly how many appeared?",
  },

  // ── TAB 2: CONFIGURE ─────────────────────────────────────
  {
    id: "step-4",
    globalNumber: 4,
    tabId: "configure",
    label: "04 / Configure",
    title: "Configure Your Preferences",
    description: "Personalise the app to match your preferences and region.",
    actionItems: [
      "Tap the Settings icon from main navigation",
      "Under Preferences → set your preferred theme (Light or Dark)",
      "Under Preferences → set your preferred language",
      "Review your currency selection and update if needed",
      "Under Social → tap Share with Friends",
      "Under Security → tap Hide Sensitive Data",
    ],
    videoUrl: "https://www.youtube.com/embed/kKNcfv5jtss?rel=0&modestbranding=1",
    trackLabel: "Configure Preferences",
    notesPlaceholder: "Any setting that was missing, unclear, or didn't work?",
  },

  // ── TAB 3: EXPLORE ───────────────────────────────────────
  {
    id: "step-5",
    globalNumber: 5,
    tabId: "explore",
    label: "05 / Explore",
    title: "Explore the Dashboard",
    description: "Explore your financial overview and key insights on the home screen.",
    actionItems: [
      "Explore the home screen and observe Today's Cashflow and your recent transactions",
      "Tap on a transaction to view its full details",
      "Navigate to the Transactions screen to browse your full transaction history",
      "Tap the utility screen (middle button) → open Annual Statistics to see your monthly spending for this year",
      "Tap on any month to view a detailed breakdown of your expenses for that period",
      "Return to Annual Statistics → use the year dropdown to switch to 2025 and review last year's spending",
    ],
    videoUrl: "https://www.youtube.com/embed/yboVsC2Ygrc?rel=0&modestbranding=1",
    hasStars: true,
    trackLabel: "Explore Dashboard",
    notesPlaceholder: "What would you improve on the dashboard?",
  },
  {
    id: "step-6",
    globalNumber: 6,
    tabId: "explore",
    label: "06 / Explore",
    title: "Transactions & Analytics",
    description: "Browse your full transaction history and dive into the analytics.",
    actionItems: [
      "Navigate to the Transactions tab from the bottom navigation",
      "Scroll through your full transaction history",
      "Use the search bar to look up a transaction by name or amount",
      "Apply filters — by date range, type (income or expense), or category",
      "Tap any transaction to open its detail view",
      "Navigate to Annual Statistics to view your monthly income, expense, and savings breakdown",
      "Use the year dropdown to browse previous years and observe your annual data",
      "Tap on a specific month to see the weekly income/expense breakdown, spending by category, and budget limits for that month",
    ],
    hasStars: true,
    trackLabel: "Transactions & Analytics",
    notesPlaceholder: "What was hard to find? What felt intuitive?",
  },

  // ── TAB 4: ORGANISE ──────────────────────────────────────
  {
    id: "step-7",
    globalNumber: 7,
    tabId: "organise",
    label: "07 / Organise",
    title: "Create Categories",
    description: "Build a category system to keep your spending organised.",
    actionItems: [
      "Go to the Categories section from the menu or navigation",
      "Tap the button to create a new category",
      "Enter the category name — start with \"Internet\"",
      "Select an icon and colour for the category, then choose the type — Expense or Income",
      "Save, then repeat the process to create an \"Airtime\" category",
      "Feel free to add any other categories that reflect your spending (e.g. Food, Transport, Savings)",
    ],
    trackLabel: "Create Categories",
    notesPlaceholder: "How intuitive was the category creation flow?",
  },
  {
    id: "step-8",
    globalNumber: 8,
    tabId: "organise",
    label: "08 / Organise",
    title: "Bulk Categorise Transactions",
    description: "Assign categories to your transactions in bulk.",
    actionItems: [
      "Navigate to Bulk Categorization from the menu",
      "Review the list of uncategorised transactions",
      "Select multiple transactions by tapping them",
      "Choose a category to assign to the selected group",
      "Tap Apply to categorise them all at once",
      "Repeat for other groups until most transactions are categorised",
    ],
    hasStars: true,
    trackLabel: "Bulk Categorise",
    notesPlaceholder: "How smooth was the bulk selection experience?",
  },
  {
    id: "step-9",
    globalNumber: 9,
    tabId: "organise",
    label: "09 / Organise",
    title: "Reinspect Annual Stats",
    description: "Review how your analytics look now that transactions are categorised.",
    actionItems: [
      "Return to the Analytics section",
      "Open the Annual Summary view",
      "Observe how the category breakdown has updated after your categorisation",
      "Check the pie or bar chart for spending distribution by category",
      "Tap individual categories to drill into the monthly breakdown",
      "Compare income vs. expense totals for the year",
    ],
    hasStars: true,
    trackLabel: "Reinspect Stats",
    notesPlaceholder:
      "How clear and useful is the analytics view after categorisation?",
  },

  // ── TAB 5: ADVANCED ──────────────────────────────────────
  {
    id: "step-10",
    globalNumber: 10,
    tabId: "advanced",
    label: "10 / Advanced",
    title: "Configure Smart Alerts",
    description: "Set up smart notifications to stay on top of your finances.",
    actionItems: [
      "Go to Smart Alerts from the menu",
      "Under Spending Insights → enable alerts for budget thresholds and unusual spending",
      "Under Transaction Intelligence → enable large transaction alerts and duplicate detection",
      "Under Goals & Savings → enable savings progress and low balance alerts",
      "Save your preferences",
      "Check the Notifications inbox to confirm alerts are appearing",
    ],
    trackLabel: "Smart Alerts",
    notesPlaceholder: "Did the alerts make sense? Were any missing or confusing?",
  },
  {
    id: "step-11",
    globalNumber: 11,
    tabId: "advanced",
    label: "11 / Advanced",
    title: "Create a Budget",
    description: "Create budgets for your spending categories.",
    actionItems: [
      "Navigate to the Budget section",
      "Tap the button to create a new budget",
      "Select a category you created earlier",
      "Set a spending limit for the budget period",
      "Choose the period — this month or a custom range",
      "Save and repeat for 2–3 of your categories",
      "Return to the dashboard and confirm budgets appear on the overview cards",
    ],
    hasStars: true,
    trackLabel: "Create a Budget",
    notesPlaceholder: "How straightforward was budget creation?",
  },
  {
    id: "step-12",
    globalNumber: 12,
    tabId: "advanced",
    label: "12 / Advanced",
    title: "Financial Plan & Goals",
    description: "Build a financial plan and set savings goals.",
    actionItems: [
      "Navigate to Financial Profile or Planning from the menu",
      "Tap Create Financial Plan",
      "Browse available plan templates → select one that fits your situation",
      "Fill in the required details — income, expenses, savings target",
      "Save the plan",
      "Within the plan or Goals section → tap to create a new savings goal",
      "Enter a goal name, target amount, and target date",
      "Save and confirm the goal appears in your profile or goals list",
    ],
    trackLabel: "Financial Goals",
    notesPlaceholder:
      "Did the planning flow make sense for how you actually think about your finances?",
  },
  {
    id: "step-13",
    globalNumber: 13,
    tabId: "advanced",
    label: "13 / Advanced",
    title: "AI Insights & Chat",
    description: "Explore AI-powered insights and chat with your financial assistant.",
    actionItems: [
      "Navigate to AI Insights from the menu",
      "Read through the generated insights and recommendations",
      "Tap an insight to expand the details",
      "Open the AI Chat feature",
      'Type a question about your finances — e.g. "Where am I overspending?" or "How can I save more?"',
      "Review the response and ask at least one follow-up question",
      "Check Chat Sessions to confirm your conversation history is saved",
    ],
    hasStars: true,
    trackLabel: "AI Insights & Chat",
    notesPlaceholder: "Any suggestions for what the AI should do better?",
  },
];

export function getStepsForTab(tabId: string): Step[] {
  return STEPS.filter((s) => s.tabId === tabId);
}

export function getStepById(id: string): Step | undefined {
  return STEPS.find((s) => s.id === id);
}
